# Basic
title: 00后
subtitle: A blog for me
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno111 Jekyll is a port of my Ghost theme vno.
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://zhaozk123456.github.io"

permalink: /:year/:month/:title/
# 必须以斜杠开始，且必须是您的仓库名称
baseurl: "/blog00x0"
# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
